# Generated by Django 5.0.1 on 2024-03-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
