# Generated by Django 5.0.1 on 2024-03-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
    ]
