# Generated by Django 5.0.1 on 2024-03-14 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bids_price_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='listing',
        ),
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bids'),
        ),
    ]
