# Generated by Django 5.0.1 on 2024-03-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flughts',
            new_name='flights',
        ),
    ]
